server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    # 微服务名: 要映射到到地址
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将查询微服务映射到/search/**
    user-service: /user/** # 将用户微服务映射到/user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**  # 将上传微服务映射到/upload/** 但是controller中还有一个upload 所以需要一下配置
      serviceId: upload-service
      strip-prefix : false
  add-host-header: true   #添加头信息 此处可解决用户登录成功后cookie保存到api.leyou.com路径不成功的问题
  sensitive-headers:      #禁止使用的头信息，设置为null，否则set-cookie无效  还要在pom文件中降版本
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: D:/leyou/rsa/rsa.pub  # 公钥地址
    cookieName: LY_TOKEN  # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/upload/image









