server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.10.10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

ly:
  jwt:
    pubKeyPath: D:/leyou/rsa/rsa.pub  # 公钥地址
    cookieName: LY_TOKEN  # cookie的名称